spring:
  profiles:
    include: real-db

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

